Portfolio/urls.py
from django.urls import path, include, re_path
from django.contrib import admin

handler404 = 'portfolio.views.handler404'
handler500 = 'portfolio.views.handler500'

urlpatterns = [
    path('s3cr3t/', admin.site.urls),
    path('accounts/', include('acct_management.urls')),
    re_path(r'^markdownx/', include('markdownx.urls')),
    path('', include('main.urls')),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('', views.BlogHomeView.as_view(), name="blog_home")
]

portfolio/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.HomeView.as_view(), name='home'),
    path('resume/', views.ResumeView.as_view(), name='resume'),
    path('curriculumvitae/', views.CurriculumVitaeView.as_view(),
         name='curriculum_vitae'),
    path('projects/', views.ProjectsView.as_view(), name='projects'),
    path('forms/addachievement', views.AddAchievementFormView.as_view(),
         name='add_achievement_form'),
    path('forms/add_skill', views.AddSkillFormView.as_view(), name='add_skill_form'),
    path('forms/add_project', views.AddProjectFormView.as_view(),
         name='add_project_form'),
]

portfolio/models.py
import uuid
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField


class Resume(models.Model):
    """Resume template builder"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    summary = models.CharField(max_length=1000)

    def __str__(self):
        return f'{self.user.get_full_name()}\'s Resume'


class CurriculumVitae(models.Model):
    """Curriculum Vitae(CV) template builder"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    summary = models.CharField(max_length=1000)

    class Meta:
        verbose_name_plural = "CVs"

    def __str__(self):
        return f'{self.user.get_full_name()}\'s CV'


class Project(models.Model):
    """A project that proves you knowledge"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cv = models.ForeignKey(
        CurriculumVitae, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=180)
    copy = MarkdownxField(max_length=3000)
    short_summary = models.CharField(max_length=250)
    summary = models.TextField(max_length=500)
    professional_development = models.BooleanField(default=False)
    field_experience = models.BooleanField(default=False)
    github_link = models.CharField(max_length=250, blank=True, null=True)
    completed = models.DateField()

    def __str__(self):
        return self.title


class Skill(models.Model):
    """
    Skills related to learning and
    advancement in school or work
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    resume = models.ForeignKey(
        Resume, on_delete=models.CASCADE, blank=True, null=True)
    cv = models.ForeignKey(
        CurriculumVitae, on_delete=models.CASCADE, blank=True, null=True)
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=180)
    copy = MarkdownxField(max_length=3000)
    summary = models.CharField(max_length=250)

    def __str__(self):
        return self.title


class WorkExperience(models.Model):
    """Jobs volunteer work and other professional experiences"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    resume = models.ForeignKey(
        Resume, on_delete=models.CASCADE, blank=True, null=True)
    cv = models.ForeignKey(
        CurriculumVitae, on_delete=models.CASCADE, blank=True, null=True)
    position = models.CharField(max_length=180)
    organization = models.CharField(max_length=180)
    summary = models.TextField(max_length=1000, blank=True, null=True)
    start = models.DateField()
    end = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.position}: {self.organization}'


class Education(models.Model):
    """An educational institute or certificate attended and achieved"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    resume = models.ForeignKey(
        Resume, on_delete=models.CASCADE, blank=True, null=True)
    cv = models.ForeignKey(
        CurriculumVitae, on_delete=models.CASCADE, blank=True, null=True)
    certificate = models.BooleanField(default=False)
    field_of_study = models.CharField(max_length=180)
    degree = models.CharField(max_length=180)
    institution = models.CharField(max_length=180)
    start = models.DateField(default=timezone.now)
    end = models.DateField(blank=True, null=True)

    def __str__(self):
        return f'{self.degree}: {self.institution}'


class Responsibility(models.Model):
    """Responsibilities performed at a Job"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    work_experience = models.ForeignKey(
        WorkExperience, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    short_summary = models.CharField(max_length=250)
    summary = models.TextField(max_length=500, blank=True, null=True)
    started = models.DateField(default=timezone.now)

    class Meta:
        verbose_name_plural = "Responsibilities"

    def __str__(self):
        return self.title


class Achievement(models.Model):
    """An achievement or accolade"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, blank=True, null=True)
    education = models.ForeignKey(
        Education, on_delete=models.CASCADE, blank=True, null=True)
    course_work = models.ForeignKey(
        'CourseWork', on_delete=models.CASCADE, blank=True, null=True)
    work_experience = models.ForeignKey(
        WorkExperience, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=180)
    short_summary = models.CharField(max_length=250)
    summary = models.TextField(max_length=500)
    completed = models.DateField()

    def __str__(self):
        return self.title


class Course(models.Model):
    """A course taken through an educational institute"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    education = models.ForeignKey(Education, on_delete=models.CASCADE)
    title = models.CharField(max_length=180)
    summary = models.TextField(max_length=500)
    end = models.DateField()

    def __str__(self):
        return self.title


class CourseWork(models.Model):
    """An assignment or project created as a part of a Course"""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=180)
    short_summary = models.CharField(max_length=250)
    summary = models.TextField(max_length=500)
    copy = MarkdownxField(max_length=3000)

    def __str__(self):
        return self.title

portfolio/views.py
import string

from django.shortcuts import render
from django.views import View
from django.contrib.auth.models import User
from django.db.models import Q

from .forms import AchievementForm, SkillForm, ProjectForm
from acct_management.models import Bio, ContactCard
from .models import CurriculumVitae, \
    Project, \
    Skill, \
    Achievement, \
    Education, WorkExperience
from markdownx.utils import markdownify

mobile_browsers = [
    'Android',
    'webOS',
    'iPhone',
    'iPad',
    'iPod',
    'BlackBerry',
    'IEMobile',
    'Opera Mini'
]

desktop_browsers = [
    'Mac',
    'Macintosh',
    'Linux',
    'Windows'
]


class HomeView(View):
    """Class based View for the Home Page"""

    bio = ""
    contact = ""
    md = None
    skills_raw = []
    skills = []
    achieves_raw = []
    achieves = []

    def __init__(self, **kwargs):
        super().__init__()
        self.main_user = User.objects.filter(
            groups__name__contains='primary_account').first()

    def get(self, request, *args, **kwargs):
        """
        Function to handle GET requests to the Home Page
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.bio = Bio.objects.filter(user=self.main_user).first()
        self.skills_raw = Skill.objects.all()
        self.skills = []
        self.achieves_raw = Achievement.objects.order_by('-completed')
        self.achieves = []

        if self.bio:
            self.md = markdownify(self.bio.copy)

        if len(self.skills_raw) >= 1:
            for skill in self.skills_raw:
                self.skills.append({
                    'id': skill.id,
                    'name': skill.title,
                    'description': skill.summary
                })

        if len(self.skills_raw) >= 1:
            for achieve in self.achieves_raw:
                self.achieves.append({
                    'id': achieve.id,
                    'name': achieve.title,
                    'description': achieve.summary
                })
        http_user = self.request.META['HTTP_USER_AGENT']
        http_user_clean = http_user.translate(
            str.maketrans('', '', string.punctuation))
        if any(item in http_user_clean.split(' ') for item in mobile_browsers):
            return render(request, 'home.html', {
                'bio': self.bio,
                'md': self.md,
                'skills': self.skills,
                'achieves': self.achieves,
                'style': 'RossDevs/css/m_style.css',
            })
        print(self.request.META['HTTP_USER_AGENT'].translate(
            str.maketrans('', '', string.punctuation)))

        return render(request, 'home.html', {
            'bio': self.bio,
            'md': self.md,
            'skills': self.skills,
            'achieves': self.achieves,
            'style': 'RossDevs/css/style.css',
        })


class AddAchievementFormView(View):
    """Class based View to handle form requests for Achievements"""

    form_class = AchievementForm
    initial = {
        'name': 'value',
        'description': 'value',
        'order': 0
    }
    template_name = 'form_template.html'

    # Create the default form.
    def get(self, request, *args, **kwargs):
        """
        Function to handle GET requests for the Achievements Form
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        form = self.form_class(initial=self.initial)
        return render(request, 'achievement_form_template.html', {'form': form})

    # Process the Form data
    def post(self, request, *args, **kwargs):
        """
        Function to handle POST requests for the Achievements Form
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        # Create a form instance and populate it with data from the request (binding):
        form = self.form_class(request.POST)

        if form.is_valid():
            new_achievement = Achievement(form.cleaned_data)
            new_achievement.save()
        return render(request, 'achievement_form_template.html', {'form': form})


class AddSkillFormView(View):
    """Class based View to handle form requests for Skills"""

    form_class = SkillForm
    initial = {
    }
    template_name = 'skill_form_template.html'

    # Create the default form.
    def get(self, request, *args, **kwargs):
        """
        Function to handle GET requests for the Skills Form
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'success': 'false'})

    # Process the Form data
    def post(self, request, *args, **kwargs):
        """
        Function to handle POST requests for the Skills Form
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        # Create a form instance and populate it with data from the request (binding):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_skill = Skill(
                name=form.cleaned_data['name'],
                description=form.cleaned_data['description'],
                highlights=form.cleaned_data['highlights'],
            )
            new_skill.save()
        return render(request, self.template_name, {
            'form': form,
            # if form is valid set the js variable "form_complete" to ture else false
            'success': ('true' if form.is_valid() else 'false')
        })


class AddProjectFormView(View):
    """Class based View to handle form requests for Projects"""

    form_class = ProjectForm
    initial = {
    }
    template_name = 'project_form_template.html'

    # Create the default form.
    def get(self, request, *args, **kwargs):
        """
        Function to handle GET requests for the Projects Form
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'success': 'false'})

    # Process the Form data
    def post(self, request, *args, **kwargs):
        """
        Function to handle POST requests for the Projects Form
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        # Create a form instance and populate it with data from the request (binding):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_obj = Project(
                name=form.cleaned_data['name'],
                short_desc=form.cleaned_data['short_desc'],
                git_link=form.cleaned_data['git_link'],
            )
            new_obj.save()
        return render(request, self.template_name, {
            'form': form,
            # if form is valid set the js variable "form_complete" to ture else false
            'success': ('true' if form.is_valid() else 'false')
        })


class CurriculumVitaeView(View):
    """
    Class based view for the Curriculum Vitae
    (course of one’s life) page
    """

    cv = {}
    bio = {}
    contact_card = {}
    address = {}
    ed = []
    certs = []
    skills = []
    professional_experiences = []
    field_experiences = []
    professional_development = []

    def __init__(self, **kwargs):
        super().__init__()
        self.main_user = User.objects.filter(
            groups__name__contains='primary_account').first()

    def get(self, request, *args, **kwargs):
        """
        Function to handle GET requests for the Curriculum Vitae Page
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        self.cv = CurriculumVitae.objects.filter(user=self.main_user).first()
        self.bio = Bio.objects.filter(user=self.main_user).first()
        self.contact_card = ContactCard.objects.filter(
            user=self.main_user).first()
        self.address = self.contact_card.address if (
            hasattr(self.contact_card, 'address') if self.contact_card else None) else None
        self.ed = Education.objects.filter(
            cv=self.cv).filter(certificate=False).order_by('-end')
        self.certs = Education.objects.filter(
            cv=self.cv).filter(certificate=True).order_by('-end')
        self.skills = Skill.objects.filter(cv=self.cv)
        self.professional_experiences = Achievement.objects.filter(
            Q(work_experience__cv=self.cv) &
            (Q(project__field_experience=False) & Q(project__user=self.main_user))
        ).order_by('-completed')
        self.field_experiences = Achievement.objects.filter(
            (Q(project__field_experience=True) & Q(project__user=self.main_user))
        ).order_by('-completed')
        self.professional_development = Achievement.objects.filter(
            Q(course_work__course__education__in=self.ed) |
            (Q(project__professional_development=True)
             & Q(project__user=self.main_user))
        ).order_by('-completed')

        return render(request, 'curriculum_vitae.html', {
            'name': self.main_user.get_full_name() if self.main_user else '',
            'profession': self.bio.profession if self.bio else '',
            'cv': self.cv,
            'address': self.address,
            'education': self.ed,
            'certificates': self.certs,
            'skills': self.skills,
            'professional_experiences': self.professional_experiences,
            'field_experiences': self.field_experiences,
            'professional_development': self.professional_development
        })


class ProjectsView(View):
    """Class based View for the Projects page"""

    projects = []

    def get(self, request):
        """
        Function to handle GET requests for the Projects Page
        :param request:
        :return:

portfolio/templates/achievement_form_template.html
<form action="/forms/addachievement" method="post">
  {% csrf_token %} {{ form }}
  <input type="submit" value="OK" />
</form>

portfolio/templates/curriculum_vitae.html
{% extends "base.html" %}
{% load static %}
{% load markdownify %}
{% load template_loader %}
{% load my_helpers %}
{% load group_tags %}
{% block title %}Curriculum Vitae{% endblock %}
{% block page_css %}
  <link rel="stylesheet" href="{% static 'portfolio/css/standard_header.css' %}" />
  <link rel="stylesheet" href="{% static 'portfolio/css/curriculum_vitae.css' %}" />
{% endblock %}
{% block header %}{% standard_header user %}{% endblock %}
{% block content %}
  <div class="cv_container">
    <div class="cv_body">
      <div class="cv_header">
        <div class="cv_header container">
            <div class="name">{{ name }}</div>
            <div class="profession">{{ profession }}</div>
            {% if user.is_authenticated %}
              {% if request.user|has_group:"primary_account" %}
                {% if address %}
                  <div class="address">
                    {% if address.street_two %}
                      <div class="street">{{ address.street_one }} {{ address.street_two }}</div>
                    {% else %}
                      <div class="street">{{ address.street_one }}</div>
                    {% endif %}
                    <div class="city">{{ address.city }},</div>
                    <div class="state">{{ address.state }},</div>
                    <div class="zip">{{ address.zip }}</div>
                  </div>
                {% endif %}
              {% endif %}
            {% endif %}
        </div>
      </div>
      <div class="summary">{{ cv.summary }}</div>
      <div class="vertical_rule"></div>
      <div class="cv_list">
        <div class="education">
          <div class="title">
            <div class="bullet">{% svg_by_name "CVSchoolIcon" %}</div>
            <div class="text">Education</div>
          </div>
          <div class="list">
            {% for ed in education %}
              <div class="education item">
                <div class="bullet">{% svg_by_name "CVBulletPoint" %}</div>
                <div class="year">{{ ed.end.year }}</div>
                <div class="degree">{{ ed.degree }}</div>
                <div class="institution">{{ ed.institution }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="certificates">
          <div class="title">
            <div class="bullet">{% svg_by_name "CVCertificates" %}</div>
            <div class="text">Certifications</div>
          </div>
          <div class="list">
            {% for cert in certificates %}
              <div class="education item">
                <div class="bullet">{% svg_by_name "CVBulletPoint" %}</div>
                <div class="year">{{ cert.end.year }}</div>
                <div class="degree">{{ cert.degree }}</div>
                <div class="institution">{{ cert.institution }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="skills">
          <div class="title">
            <div class="bullet">{% svg_by_name "CVSkillsIcon" %}</div>
            <div class="text">Skills</div>
          </div>
          <div class="list">
            <div class="skill item">
              <div class="bullet">{% svg_by_name "CVBulletPoint" %}</div>
              <div class="skills inner">
                {% for skill in skills %}
                  <div class="dot"></div>
                  <div class="skill">{{ skill.title }}</div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        <div class="professional_experience">
          <div class="title">
            <div class="bullet">{% svg_by_name "CVWorkIcon" %}</div>
            <div class="text">Professional Experience</div>
          </div>
          <div class="list">
            {% for experience in professional_experiences %}
              <div class="achievement item">
                <div class="bullet">{% svg_by_name "CVBulletPoint" %}</div>
                <div class="year">{{ experience.completed.year }}</div>
                <div class="title">{{ experience.title }}</div>
                <div class="summary">{{ experience.summary }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="field_experience">
          <div class="title">
            <div class="bullet">{% svg_by_name "CVFeildExperience" %}</div>
            <div class="text">Field Experience</div>
          </div>
          <div class="list">
            {% for experience in field_experiences %}
              <div class="achievement item">
                <div class="bullet">{% svg_by_name "CVBulletPoint" %}</div>
                <div class="year">{{ experience.completed.year }}</div>
                <div class="title">{{ experience.title }}</div>
                <div class="summary">{{ experience.summary }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="professional_development">
          <div class="title">
            <div class="bullet">{% svg_by_name "CVDevelopment" %}</div>
            <div class="text">Professional Development</div>
          </div>
          <div class="list">
            {% for development in professional_development %}
              <div class="achievement item">
                <div class="bullet">{% svg_by_name "CVBulletPoint" %}</div>
                <div class="year">{{ development.completed.year }}</div>
                <div class="title">{{ development.title }}</div>
                <div class="summary">{{ development.summary }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block footer %}{% large_footer %}{% endblock %}

portfolio/templates/footer.html
<div class="home footer small">
    <div class="standard links">
      <div class="line">
      <div class="sitemap"><a href="{% url 'sitemap' %}">Sitemap</a></div>
      <div class="dot"></div>
      <div class="privacy_policy"><a href="{% url 'privacy_policy' %}">Privacy Policy</a></div>
      <div class="dot"></div>
      <div class="security_policy"><a href="{% url 'security_policy' %}">Security Policy</a></div>
    </div>
    <div class="line">
      <div class="about"><a href="{% url 'about' %}">About</a></div>
      <div class="dot"></div>
      <div class="code_of_conduct"><a href="{% url 'code_of_conduct' %}">Code of Conduct</a></div>
    </div>
  </div>
</div>

portfolio/templates/footer_ico_link.html
{% load my_helpers %}

<div class="card">
  <a href="{{ link }}" target="_blank">
    <div class="icon">{% svg_by_name svg_name %}</div>
    <span>{{ txt }}</span>
  </a>
</div>

portfolio/templates/large_footer.html
{% load my_helpers %}

<div class="home footer">
  {% socials %}
  <div class="standard links">
      <div class="line">
      <div class="sitemap"><a href="{% url 'sitemap' %}">Sitemap</a></div>
      <div class="dot"></div>
      <div class="privacy_policy"><a href="{% url 'privacy_policy' %}">Privacy Policy</a></div>
      <div class="dot"></div>
      <div class="security_policy"><a href="{% url 'security_policy' %}">Security Policy</a></div>
    </div>
    <div class="line">
      <div class="about"><a href="{% url 'about' %}">About</a></div>
      <div class="dot"></div>
      <div class="code_of_conduct"><a href="{% url 'code_of_conduct' %}">Code of Conduct</a></div>
    </div>
  </div>
</div>

portfolio/templates/project.html
{% extends "base.html" %}
{% load static %}
{% load template_loader %}
{% block title %}{% endblock %}
{% block page_css %}
  <link rel="stylesheet" href="{% static 'portfolio/css/standard_header.css' %}" />
  <link rel="stylesheet" href="{% static 'portfolio/css/project.css' %}" />
{% endblock %}
{% block header %} {% standard_header user %} {% endblock %}
{% block content %}
  <div class="project_container">
    <div class="project_body">
    </div>
  </div>
{% endblock %}
{% block footer %}{% standard_footer %}{% endblock %}

portfolio/templates/project_form_template.html
{% extends 'form_base.html' %}
{% load static %}
{% block css %}
<link
  rel="stylesheet"
  href="{% static 'portfolio/css/project_form_style.css' %}"
/>
{% endblock %}
{% block js %}
<script src="{% static 'portfolio/js/project_form_functions.js' %}"></script>
{% endblock %}
{% block content %}
<script>
  let form_complete = {{ success }};
</script>
<form class="project_form" action="/forms/add_project" method="post">
  {% csrf_token %}
  {% for field in form %}
  <label class="label_{{ field.auto_id }}" for="{{ field.auto_id }}">
      {{ field.label }}
  </label>
  {{ field }}
  {% endfor %}
  <input class="submit" type="submit" value="ADD" />
</form>
{% endblock %}

portfolio/templates/resume.html
{% extends "base.html" %}
{% load group_tags %}
{% load static %}
{% load template_loader %}
{% block title %}Resume{% endblock %}
{% block page_css %}
  <link rel="stylesheet" href="{% static 'portfolio/css/standard_header.css' %}" />
  <link rel="stylesheet" href="{% static 'portfolio/css/resume.css' %}" />
{% endblock %}
{% block header %}{% standard_header user %}{% endblock %}
{% block content %}
  <div class="resume container">
    <div class="resume body">
      <div class="resume header">
        <div class="header_text">
          {{ main_user_name }}
        </div>
        <svg class="horizontal_rule" viewBox="0 0 859 2" xmlns="http://www.w3.org/2000/svg">
          <path stroke-width="2" d="M0 1H859"></path>
        </svg>
      </div>
      <div class="resume sidebar">
        {% if user.is_authenticated %}
          {% if request.user|has_group:"primary_account" %}
            <span>{{ phone }}</span>
          {% endif %}
        {% endif %}
        <span>{{ email }}</span>
        <span>{{ website }}</span>
      </div>
      <div class="resume main content">
        <div class="summary inner container">
          <div class="summary title">Summary</div>
          <div class="summary block">{{ resume.summary }}</div>
        </div>
        <div class="skills inner container">
          <div class="skills title">Technical Skills</div>
          <div class="skills block">
            {% for skill in resume.skill_set.all %}
              <div class="skill">
                <div class="dot"></div>
                <div class="name">{{ skill.title }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="achievements inner container">
          <div class="achievements title">Achievments</div>
          <div class="achievements block">
            {% for achievement in achievements %}
              <div class="achievement">{{ achievement.short_summary }}</div>
            {% endfor %}
          </div>
        </div>
        <div class="work-experience inner container">
          <div class="work-experience title">Work Experience</div>
          <div class="work-experience block">
            {% for work_experience in work_experiences %}
              <div class="work">
                <div class="work head">
                  <div class="position">{{ work_experience.position }}</div>
                  <div class="long dash"></div>
                  <div class="organization">{{ work_experience.organization }}</div>
                  <div class="long dash"></div>
                  <div class="start">{{ work_experience.start }}</div>
                  <div class="dash"></div>
                  {% if  work_experience.end %}
                    <div class="end">{{ work_experience.end }}</div>
                  {% else %}
                    <div class="end">Current</div>
                  {% endif %}
                </div>
                <div class="responsibilities">
                  {% for responsibility in work_experience.responsibilities %}
                    <div class="responsibility">
                      <div class="dot"></div>
                      <div class="short summary">{{ responsibility.short_summary }}</div>
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        <div class="education inner container">
          <div class="education title">Education</div>
          <div class="education block">
            {% for ed in education  %}
              <div class="education-inner">
                <div class="degree">{{ ed.degree }}</div>
                <div class="long dash"></div>
                <div class="institute">{{ ed.institution }}</div>
                <div class="long dash"></div>
                <div class="year">{{ ed.end.year }}</div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block footer %}{% large_footer %}{% endblock %}

portfolio/templates/small_header.html
{% load static %}
{% url 'home' as home %}
{% block header_css %}
<link rel="stylesheet" href="{% static 'portfolio/css/standard_header.css' %}" />
{% endblock %}
<div class="small_header header">
  <nav class="nav-bar">
    <a href="{{ home }}">Home</a>
    {% if user.is_authenticated %}
      <a href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}">Login</a>
    {% endif %}
  </nav>
</div>

portfolio/templates/social.html
{% load my_helpers %}

<div class="social">
    {% for soc in socials %}
        {% footer_icon soc.txt soc.link soc.svg_name %}
    {% endfor %}
</div>